Repository pepfar-datim/datapackr, pull requests merged in 2022-03, with the labels that each got.

#390 Code cleanup
  NAMESPACE
  R/evaluate_indicators.R
  R/fetch_prioritization_table.R
  R/generateApprovalMemoDOCX.R
  R/generate_approval_memo.R
  R/get_memo_indicators.R
  R/memo_structure.R
  R/packageSetup.R
  R/prepareMemoData.R
  R/prepare_memo_data.R
  R/update_existing_prioritization.R
  man/add_dp_psnu.Rd
  man/datapackr_params.Rd
  man/default_memo_font.Rd
  man/default_memo_style_header.Rd
  man/default_memo_style_para.Rd
  man/evaluateIndicators.Rd
  man/evaluate_indicators.Rd
  man/fetchPrioritizationTable.Rd
  man/fetch_prioritization_table.Rd
  man/generateApprovalMemo.Rd
  man/generateMemoTemplate.Rd
  man/generate_approval_memo.Rd
  man/generate_memo_template.Rd
  man/getCountries.Rd
  man/getMechanismView.Rd
  man/get_memo_indicators.Rd
  man/memo_structure.Rd
  man/parameter-checks.Rd
  man/prepareExistingDataAnalytics.Rd
  man/prepareMemoData.Rd
  man/prepareMemoDataByPSNU.Rd
  man/prepareMemoDataByPartner.Rd
  man/prepareMemoDataByPrio.Rd
  man/prepareMemoMetadata.Rd
  man/prepare_existing_data_analytics.Rd
  man/prepare_memo_data.Rd
  man/prepare_memo_data_by_agency.Rd
  man/prepare_memo_data_by_partner.Rd
  man/prepare_memo_data_by_prio.Rd
  man/prepare_memo_data_by_psnu.Rd
  man/prepare_memo_metadata.Rd
  man/reexports.Rd
  man/renderPartnerTable.Rd
  man/renderPrioTable.Rd
  man/render_agency_table.Rd
  man/render_partner_table.Rd
  man/render_prio_table.Rd
  man/updateExistingPrioritization.Rd
  man/update_existing_prioritization.Rd
  man/zeros_to_dashes.Rd
  tests/testthat/test-get-memo-indicators.R
  tests/testthat/test-indicators.R
  tests/testthat/test-memo-structure.R
Labels: type: CODE CLEANUP 🧹, type: DOCUMENTATION 📖

#397 Dp 241
  R/checkFormulas.R
Labels: tool: DATA PACK 🎒, process: PROCESSING ⚙️, type: CODE CLEANUP 🧹

#400 Removes unnecessary use of `:::`
  tests/testthat/test-checkComments.R
  tests/testthat/test-checkStructure.R
  tests/testthat/test-create-analytics.R
  tests/testthat/test-handshake.R
  tests/testthat/test-resolve-dedupes.R
  tests/testthat/test-signature.R
  tests/testthat/test-unpack-COP21-datapack.R
Labels: type: CODE CLEANUP 🧹

#398 Dp 523
  R/checkStructure.R
  R/unPackSNUxIM.R
  R/unPackSheet.R
Labels: type: BUG 🐛, cycle: COP 🌍, tool: DATA PACK 🎒, process: PROCESSING ⚙️

#409 Release Candidate 5.1.6
  .lintr
  DESCRIPTION
  NEWS.md
  R/adornMechanisms.R
  R/adorn_import_file.R
  R/checkColStructure.R
  R/checkFormulas.R
  R/checkMechanisms.R
  R/checkMissingMetadata.R
  R/checkPSNUData.R
  R/checkStructure.R
  R/check_params.R
  R/createAnalytics.R
  R/evaluateIndicators.R
  R/fetchPrioritizationTable.R
  R/generateApprovalMemo.R
  R/generateComparisonTable.R
  R/getCOPDataFromDATIM.R
  R/getPSNUs.R
  R/loadDataPack.R
  R/packDataPackSheet.R
  R/packPSNUxIM.R
  R/packSNUxIM_2020.R
  R/packageSetup.R
  R/prepareMemoData.R
  R/unPackSNUxIM.R
  R/unPackSchema.R
  R/unPackSheet.R
  R/updateExistingPrioritization.R
  R/utilities.R
  R/validationSummary.R
  R/writePSNUxIM.R
  man/adorn_import_file.Rd
  man/checkHasPSNUxIM.Rd
  man/datapackr_params.Rd
  man/getMaxCores.Rd
  man/getMechanismView.Rd
  man/prepareMemoDataByAgency.Rd
  man/prepareMemoDataByPSNU.Rd
  man/prepareMemoDataByPrio.Rd
  man/renderAgencyTable.Rd
  man/renderPartnerTable.Rd
  man/renderPrioTable.Rd
  man/updateExistingPrioritization.Rd
  man/writePSNUxIM.Rd
  tests/testthat/play.dhis2.org/2.36.1/api/36/dataValueSets.csv-c2768a.R
  tests/testthat/test-checkComments.R
  tests/testthat/test-checkNeedsPSNUxIM.R
  tests/testthat/test-checkStructure.R
  tests/testthat/test-create-analytics.R
  tests/testthat/test-fetchPrioritizations.R
  tests/testthat/test-handshake.R
  tests/testthat/test-prepareMemoData.R
  tests/testthat/test-resolve-dedupes.R
  tests/testthat/test-signature.R
  tests/testthat/test-unpack-COP21-datapack.R
  tests/testthat/training.datim.org/api/analytics.json-f5b410.json
Labels: process: PROCESSING ⚙️, type: CODE CLEANUP 🧹, type: REFACTORING 🛠

#414 Remove unused parameters
  R/deriveTargets.R
  R/getOPUDataFromDATIM.R
  man/deriveTargets.Rd
  man/getOPUDataFromDATIM.Rd
Labels: type: CODE CLEANUP 🧹, type: DOCUMENTATION 📖

#412 Lint whole package in checks
  .circleci/config.yml
  tests/testthat/test-checkNeedsPSNUxIM.R
  tests/testthat/test-create-schema.R
  tests/testthat/test-fetchPrioritizations.R
  tests/testthat/test-get-memo-indicators.R
  tests/testthat/test-getNumeratorDenominator.R
  tests/testthat/test-indicators.R
  tests/testthat/test-prepareMemoData.R
  tests/testthat/test-pull-code-list.R
Labels: type: CODE CLEANUP 🧹

#417 Add missing `d2_session` parameter
  R/utilities.R
  man/getCountries.Rd
Labels: type: CODE CLEANUP 🧹

#415 Align output folder parameters
  R/create_play_spectrum_output.R
  R/exportPackr.R
  R/packDataPack.R
  R/packOPUDataPack.R
  R/packageSetup.R
  R/writePSNUxIM.R
  data-raw/COP21OPU_Data_Pack_processing_script.R
  data-raw/COP21_Data_Pack_processing_script.R
  data-raw/extract-spectrum-data.R
  man/create_play_spectrum_output.Rd
  man/datapackr_params.Rd
  man/exportPackr.Rd
  man/packDataPack.Rd
  man/packOPUDataPack.Rd
  man/parameter-checks.Rd
  man/writePSNUxIM.Rd
Labels: type: CODE CLEANUP 🧹, type: DOCUMENTATION 📖

#413 Dp 547
  R/utilities.R
  tests/testthat/test-utilities.R
Labels: cycle: COP 🌍, tool: DATA PACK 🎒, process: PROCESSING ⚙️, type: DEPRECATION ♻️ 🗑
