Repository pepfar-datim/datapackr, pull requests merged in 2022-05, with the labels that each got.

#451 DP-642: Deprecate old `datapackr` functionality
  NAMESPACE
  R/adornPSNUs.R
  R/deriveTargets.R
  R/getMechanismView.R
  R/getNumeratorDenominator.R
  R/getValidCOs.R
  R/packForPAW.R
  R/pullCOPindicators.R
  R/pullTechArea.R
  R/utilities.R
  man/adornMechanisms.Rd
  man/adornPSNUs.Rd
  man/deriveTargets.Rd
  man/getCountries.Rd
  man/getIMPATTLevels.Rd
  man/getMechanismView.Rd
  man/getMechanismViewFromDATIM.Rd
  man/getNumeratorDenominator.Rd
  man/getTechArea.Rd
  man/getValidCOs.Rd
  man/packForPAW.Rd
  man/prepareMemoDataByPartner.Rd
  man/pull_COPindicators.Rd
  tests/testthat/test-getMechanismView.R
  tests/testthat/test-getNumeratorDenominator.R
  tests/testthat/test-pull-code-list.R
Labels: type: DEPRECATION ♻️ 🗑, type: DOCUMENTATION 📖

#455 DP-682: Retire `getValidCategoryOptions`
  NAMESPACE
  R/data.R
  R/getValidCategoryOptions.R
  data-raw/update_cached_valid_COs.R
  data/valid_category_options.rda
  man/getValidCategoryOptions.Rd
  man/valid_category_options.Rd
Labels: type: DEPRECATION ♻️ 🗑

#470 DP-525: Add test for message level consistency
  R/messageQueue.R
Labels: type: TESTS 🔬🧪

#464 Clear warnings and notes from build checks
  .Rbuildignore
  DESCRIPTION
  R/checkPSNUData.R
  R/createAnalytics.R
  R/datapackr.R
  R/evaluateIndicators.R
  R/generateApprovalMemo.R
  R/prepareMemoData.R
  R/updateExistingPrioritization.R
  R/utilities.R
  man/evaluateIndicators.Rd
  man/formatSetStrings.Rd
  man/generateMemoTemplate.Rd
  man/prepareMemoData.Rd
  man/renderAgencyTable.Rd
  man/renderPartnerTable.Rd
  man/renderPrioTable.Rd
  man/updateExistingPrioritization.Rd
  man/zerosToDashes.Rd
Labels: type: CODE CLEANUP 🧹, type: DOCUMENTATION 📖

#474 Stop parallelization on Windows
  R/checkPSNUData.R
  R/prepareMemoData.R
Labels: type: BUG 🐛

#478 DP-667: Reduce cyclomatic complexity of `writePSNUxIM`
  R/writePSNUxIM.R
  man/writePSNUxIM.Rd
Labels: type: REFACTORING 🛠

#475 DP-661: Reduces cyclomatic complexity of `packPSNUxIM`
  R/packPSNUxIM.R
Labels: type: REFACTORING 🛠

#471 Dp 610 2
  DESCRIPTION
  NAMESPACE
  R/getMechanismView.R
  man/getMechanismViewFromDATIM.Rd
  renv.lock
  tests/testthat/test-getMechanismView.R
  tests/testthat/training.datim.org/api/sqlViews/fgUtV6e9YIX/data.csv-3b3c4f.json
  tests/testthat/training.datim.org/api/sqlViews/fgUtV6e9YIX/data.json-0df321.json
  tests/testthat/training.datim.org/api/sqlViews/fgUtV6e9YIX/data.json-359174.json
  tests/testthat/training.datim.org/api/sqlViews/fgUtV6e9YIX/data.json-3b3c4f.json
Labels: tool: DATA PACK 🎒, process: MODEL DATA 📊, type: DEPRECATION ♻️ 🗑, type: CODE CLEANUP 🧹, type: REFACTORING 🛠, type: TESTS 🔬🧪
