Repository pepfar-datim/datapackr, pull requests merged in 2022-06, with the labels that each got.

#498 Expands unit tests
  NAMESPACE
  R/checkPSNUData.R
  R/prepareMemoData.R
  R/utilities.R
  man/can_spawn.Rd
  man/checkPSNUData.Rd
  man/prepareMemoData.Rd
  man/prepareMemoDataByPSNU.Rd
  tests/testthat/test-checkPSNUData.R
  tests/testthat/test-prepareMemoData.R
Labels: type: TESTS 🔬🧪

#500 DP-605: Refactor `map_Cs_to_COCs`
  R/map_Cs_to_COs.R
  tests/testthat/training.datim.org/api/categories.json-6b391d.json
Labels: type: REFACTORING 🛠

#499 DP-597: Refactor `getHTSModality` to utilize `datimutils`
  R/getHTSModality.R
  R/pullHTSModality.R
  man/getHTSModality.Rd
  tests/testthat/test-getHTSModality.R
  tests/testthat/training.datim.org/api/33/dataElementGroupSets/ra9ZqrTtSQn.json-25a82e.json
  tests/testthat/training.datim.org/api/dataElementGroupSets.json-c713e8.json
Labels: type: REFACTORING 🛠

#460 Make unallocated data DSD/TA agnostic
  R/writePSNUxIM.R
Labels: process: GENERATION 🏗, tool: OPU/PSNUxIM ⚖️

#508 DP-599: Merges `pullDATIMCodeList` into `pullFullCodeList`
  DESCRIPTION
  NAMESPACE
  R/getCodeList.R
  R/pullDATIMCodeList.R
  R/pullFullCodeList.R
  data-raw/COP21_Data_Pack_processing_script.R
  data-raw/test_datasets.R
  data-raw/update_cached_de_coc_co_map.R
  data-raw/update_cop22_de_coc_co_map.R
  man/getCodeList.Rd
  man/pullDATIMCodeList.Rd
  tests/testthat/test-get-code-list.R
Labels: type: REFACTORING 🛠

#476 DP-662: Reduce cylomatic complexity of `packSNUxIM`
  R/packSNUxIM.R
Labels: type: REFACTORING 🛠

#515 DP-693: Remove the usage of `readr` package
  DESCRIPTION
  R/datapackr.R
  R/exportPackr.R
  R/getCodeList.R
  R/getDataValueSets.R
  man/exportPackr.Rd
  man/getCodeList.Rd
  man/getDataValueSets.Rd
  man/parameter-checks.Rd
Labels: type: REFACTORING 🛠, type: DOCUMENTATION 📖
